ERROR - 2025-06-02 00:58:20 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 00:58:23 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 00:58:43 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 00:58:45 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 00:59:46 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:02:49 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:03:31 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:05:43 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:24:38 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:37:56 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:42:16 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-06-02 01:47:44 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(35): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-06-02 01:53:05 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "exito.php"
[Method: GET, Route: setup/exito]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('exito.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('exito', [], true)
 3 APPPATH\Controllers\SetupController.php(56): view('exito', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\SetupController->exito()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-02 01:55:45 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "exito.php"
[Method: GET, Route: setup/exito]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('exito.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('exito', [], true)
 3 APPPATH\Controllers\SetupController.php(56): view('exito', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\SetupController->exito()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-02 02:22:30 --> mysqli_sql_exception: Duplicate entry 'demo@email.com' for key 'usuarios.email' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\wamp64\www\proyecto\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\wamp64\www\proyecto\app\Database\Seeds\UsuarioSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\proyecto\system\Database\Seeder.php(149): App\Database\Seeds\UsuarioSeeder->run()
#6 C:\wamp64\www\proyecto\app\Controllers\SetupController.php(40): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\SetupController->index()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SetupController))
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
