ERROR - 2025-05-31 00:15:49 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\Setup.php(37): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-05-31 00:15:49 --> mysqli_sql_exception: Table 'juego.usuarios' doesn't exist in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\wamp64\www\proyecto\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\wamp64\www\proyecto\app\Database\Seeds\UsuarioSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\proyecto\system\Database\Seeder.php(149): App\Database\Seeds\UsuarioSeeder->run()
#6 C:\wamp64\www\proyecto\app\Controllers\Setup.php(46): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-31 00:20:00 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\Setup.php(37): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-05-31 00:20:00 --> mysqli_sql_exception: Table 'juego.usuarios' doesn't exist in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\wamp64\www\proyecto\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\wamp64\www\proyecto\app\Database\Seeds\UsuarioSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\proyecto\system\Database\Seeder.php(149): App\Database\Seeds\UsuarioSeeder->run()
#6 C:\wamp64\www\proyecto\app\Controllers\Setup.php(46): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-31 02:58:13 --> mysqli_sql_exception: Duplicate entry 'demo@email.com' for key 'usuarios.email' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\wamp64\www\proyecto\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\wamp64\www\proyecto\app\Database\Seeds\UsuarioSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\proyecto\system\Database\Seeder.php(149): App\Database\Seeds\UsuarioSeeder->run()
#6 C:\wamp64\www\proyecto\app\Controllers\Setup.php(45): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-31 02:59:15 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\Setup.php(36): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-05-31 02:59:50 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\Setup.php(36): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-05-31 03:09:18 --> mysqli_sql_exception: Invalid default value for 'creado_en' in C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\proyecto\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\proyecto\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\proyecto\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\proyecto\app\Database\Migrations\2025-05-30-182129_CreateUsuario.php(20): CodeIgniter\Database\Forge->createTable('usuarios')
#5 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsuario->up()
#6 C:\wamp64\www\proyecto\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\proyecto\app\Controllers\Setup.php(36): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\wamp64\www\proyecto\system\CodeIgniter.php(933): App\Controllers\Setup->index()
#9 C:\wamp64\www\proyecto\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setup))
#10 C:\wamp64\www\proyecto\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\proyecto\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\wamp64\www\proyecto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\wamp64\www\proyecto\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
